# Generated by Django 5.2.1 on 2025-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('whistleblower', 'Whistleblower'), ('organization_free', 'Org - Free'), ('organization_premium', 'Org - Premium'), ('admin', 'Admin')], default='whistleblower', max_length=30),
        ),
    ]
