# Generated by Django 5.2.1 on 2025-05-21 08:14

import django.db.models.deletion
import encrypted_model_fields.fields
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='is_resolved',
            new_name='is_premium',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolution_notes',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('abuse', 'Abuse'), ('corruption', 'Corruption'), ('harassment', 'Harassment'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.user_report_path),
        ),
        migrations.AddField(
            model_name='report',
            name='priority_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
