# Generated by Django 5.2.1 on 2025-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
