# Generated by Django 5.2.1 on 2025-05-22 12:49

import django.db.models.deletion
import reports.models
import reports.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_is_anonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.user_report_path, validators=[reports.validators.validate_upload_file]),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
