# Generated by Django 5.2.1 on 2025-05-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_internal_notes_report_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_anonymous',
        ),
    ]
