# Generated by Django 5.2.1 on 2025-06-02 16:52

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_organization_rename_is_image_report_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccessrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminaccessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_reviewed', to='reports.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_status_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
