# Generated by Django 5.2.1 on 2025-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_adminaccessrequest_notes_report_is_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
