# Generated by Django 5.2.1 on 2025-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('canclelled', 'Cancelled'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
